### ISSUE TITLE
System.DllNotFoundException: ole32.dll

### ISSUE THREAD

**Issue by FlimFlam** [graealex/CSL-SpaceMouse#1]
I would love to use this mod because I am very used to use my spacemouse for CAD and grab it intuitively every few minutes. But I just get an error message when starting the game:

The Mod /Users/maik.pfaffenrath/Library/Application Support/Steam/steamapps/workshop/content/255710/2021361606 [Interop.TDxInput.dll, CSLSpaceMouse.dll] has caused an error [ModException]

Details:
System.DllNotFoundException: ole32.dll
at (wrapper managed-to-native) System.__ComObject:CoCreateInstance (System.Guid,intptr,uint,System.Guid,intptr

My CSL version is up to date and I'm on macOS Catalina on my MacPro.
Does anyone else have the same problem? I would really appreciate help because I'm very new to cities:skylines.

**Comment by graealex** [comment]
Unfortunately, this mod is Windows-only, and right now I have no plans on porting it, as the SDKs on macOS and Windows are pretty different.
